### PR TITLE
added api key error handling

### PR DESCRIPTION
**Pull request by sdthaker**
## Issue
* Fixes issue #52 

## Changes made
* Added API error handling by introducing try and catch block in handleSubmit
* If there's any error related to the Youtube API key, the user is shown the proper log on the console

## Changes in action
image

## Additional Notes
Please let me know if you want something added/removed as part of this PR, eg. if you'd want me to change the logic of how I'm handling the error, any more details to be shown on console, etc. @arjxn-py

### CODE REVIEW

**Review by arjxn-py — COMMENTED** [review]
Thanks @sdthaker, looks good to me.
We can also display the error on the page as well other than console between the searchbar & underheader.

**Comment by sdthaker** [comment]
> Thanks @sdthaker, looks good to me.
> 
> We can also display the error on the page as well other than console between the searchbar & underheader.

Sure! Any specific UI requiments for the error message?

**Comment by arjxn-py** [comment]
> Sure! Any specific UI requiments for the error message?

For now it should just simply look like a general error in red color with project friendly font style and properly aligned size around 12-14px should be nice.

**Comment by sdthaker** [comment]
Changes with commit [22d2ccc](https://github.com/Curio-org/Curio/pull/57/commits/22d2ccc42ce8e8938e5bb05e453d6c88a2224876):

For >768px screens:
image

For <= 768px screens
image

Please let me know if anything needs to be changed for the commit.

**Review by arjxn-py — APPROVED** [review]
Thanks @sdthaker, looks perfect.
Nice work 🚀

**Pull request merged**
